### ISSUE TITLE
/ocpu/tmp/{key}/zip fails on CentOS6 with "warning! error 1 in extracting from zip file"

### ISSUE THREAD

**Issue by mbacou** [jeroenooms/opencpu#120]
First I noticed I had to manually set option `zip="zip"` to my own package `zip()` calls or else no ZIP archive was generated. I then tried a couple of things:

 - manually added `export R_ZIPCMD=zip` to `/etc/environment`
 - added `options(zip="zip")` to `/etc/opencpu/Rprofile`

That's not helping. I still receive the same error when requesting `/ocpu/tmp/{key}/zip`. Likely another CentOS oddity, but I'm a bit at a loss.

Here is an example:

```sh
$ curl http://hcapi.harvestchoice.org/ocpu/library/hcapi3/R/genFile -d "var='whea_h'&iso3='TZA'&format='dta'" -X POST
/ocpu/tmp/x01b8881843/R/.val
/ocpu/tmp/x01b8881843/messages
/ocpu/tmp/x01b8881843/stdout
/ocpu/tmp/x01b8881843/source
/ocpu/tmp/x01b8881843/console
/ocpu/tmp/x01b8881843/info
/ocpu/tmp/x01b8881843/files/DESCRIPTION
/ocpu/tmp/x01b8881843/files/README
/ocpu/tmp/x01b8881843/files/whea_h-TZAdta.dta

$ curl http://hcapi.harvestchoice.org/ocpu/tmp/x01b8881843/zip -X POST
warning! error 1 in extracting from zip file
```

**Comment by parisni** [comment]
Hello,
No idea/workaround to make zip working on centos ?
Thanks

**Comment by mbacou** [comment]
Yes, try to set the global R environment variable in `/usr/lib64/R/etc/Renviron`. Seems to work on CentOS 6.

```
# /usr/lib64/R/etc/Renviron

R_ZIPCMD=${R_ZIPCMD-'/usr/bin/zip'}
```

**Comment by mbacou** [comment]
One remaining problem though is the session ZIP archive is simply named `zip` (no filename, no extension), e.g.:


```
$ wget http://hcapi.harvestchoice.org/ocpu/tmp/x009dcc1d41/zip
--2016-07-01 21:11:47--  http://hcapi.harvestchoice.org/ocpu/tmp/x009dcc1d41/zip
Resolving hcapi.harvestchoice.org... 206.190.150.74
Connecting to hcapi.harvestchoice.org|206.190.150.74|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: “zip”

    [ <=>                                             ] 311,552     --.-K/s   in 0s
```
