### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by JackStat** [jeroenooms/opencpu#128]
I have installed opencpu-full on an EC2 Ubuntu instance as well as a virtual CentOS machine.  On both machines I get a 500 Internal Server Error after opencpu has been running for several hours.  To get the error to go away I have been  using 

```
sudo service opencpu restart
```
for the Ubuntu box and 

```
sudo service restart httpd
```
for the CentOS box (it isn't recognizing opencpu as a service...).  Then after several hours the 500 Internal Server error returns.  We would like to use opencpu in production but this is a serious drawback.  Any solution?

**Comment by jeroenooms** [comment]
Strange, I have never heard this. The public server has been running for years without any restarts. Maybe you're running out of disk space or so?

Whenever apache returns a 500, you can usually see what is going wrong in the error logs. Have a look at

    sudo tail /var/log/apache2/error.log

or 

    sudo tail /var/log/opencpu/apache_error.log

Perhaps there is a hint in there on what is going wrong.

**Comment by JackStat** [comment]
I see this in the

```
sudo tail /var/log/opencpu/apache_error.log
```


```
[Mon Jan 05 07:15:04.553056 2015] [core:error] [pid 15096] [client 198.20.69.74:34138] AH00135: Invalid method in request quit
[Mon Jan 05 15:20:47.305465 2015] [:error] [pid 17441] [client 50.200.131.35:2249] rApache Notice!
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/ocpu-temp/file44214e7ed958': No such file or directory
Traceback:
No traceback available 
```


and this in 

```
sudo tail /var/log/kern.log
```

```
Jan  5 15:27:44 ip-172-31-6-18 kernel: [421864.544081] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:28:16 ip-172-31-6-18 kernel: [421896.608110] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:28:48 ip-172-31-6-18 kernel: [421928.672085] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:29:20 ip-172-31-6-18 kernel: [421960.736123] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:29:52 ip-172-31-6-18 kernel: [421992.800075] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:30:24 ip-172-31-6-18 kernel: [422024.864109] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:30:56 ip-172-31-6-18 kernel: [422056.928110] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:31:28 ip-172-31-6-18 kernel: [422088.992100] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:32:01 ip-172-31-6-18 kernel: [422121.056089] xen:balloon: reserve_additional_memory: add_memory() failed: -17
Jan  5 15:32:33 ip-172-31-6-18 kernel: [422153.120082] xen:balloon: reserve_additional_memory: add_memory() failed: -17

```

**Comment by JackStat** [comment]
On the CentOS box I could find the same logs but the log for httpd had this

```
[Sun Jan 04 16:26:50 2015] [crit] [client 10.1.70.78] configuration error:  couldn't perform authentication. AuthType not set!: /favicon.ico
[Sun Jan 04 16:29:10 2015] [error] [client 10.1.70.78] Directory index forbidden by Options directive: /var/www/html/
[Sun Jan 04 16:29:11 2015] [crit] [client 10.1.70.78] configuration error:  couldn't perform authentication. AuthType not set!: /favicon.ico
[Sun Jan 04 16:34:32 2015] [error] [client 10.1.70.78] rApache Notice!
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/ocpu-temp/file3ca4520110a': No such file or directory
Traceback:
```

**Comment by jeroenooms** [comment]
Hmm seems like your temp files go missing. How are you doing on disk space in `/tmp`? Try

    df -ah

**Comment by JackStat** [comment]
Hmm.  That doesn't seem to be it.  Here are the results
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  1.7G  5.7G  23% /
proc               0     0     0    - /proc
sysfs              0     0     0    - /sys
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none               0     0     0    - /sys/fs/fuse/connections
none               0     0     0    - /sys/kernel/debug
none               0     0     0    - /sys/kernel/security
udev            1.9G   12K  1.9G   1% /dev
devpts             0     0     0    - /dev/pts
tmpfs           377M  352K  377M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            1.9G     0  1.9G   0% /run/shm
none            100M     0  100M   0% /run/user
none               0     0     0    - /sys/fs/pstore
systemd            0     0     0    - /sys/fs/cgroup/systemd
/dev/xvdb        15G   39M   15G   1% /mnt
```


I did a fresh build EC2 c3.large instance.  I installed everything like this.
```
sudo add-apt-repository ppa:opencpu/opencpu-1.4
sudo apt-get update
sudo apt-get install opencpu
sudo apt-get install rstudio-server #optional

sudo apt-get install libcurl-openssl-dev
```

Then I installed a couple R packages.  I didn't make any requests or utilize the API in any way and some time later the 500 Internal Server Error popped up again.  The apache log was empty but I did get the same error as I did previously in the kern.log

```
xen:balloon: reserve_additional_memory: add_memory() failed: -17
```

**Comment by jeroenooms** [comment]
Mmm the kern.log error seems to be a [general ec2 error](http://serverfault.com/questions/620705/xenballoon-reserve-additional-memory-add-memory-failed-17), not directly related to opencpu.

I haven't seen this problem anywhere. Which packages did you install? Can you give me a shell to one of the ec2 instances when it is broken?

**Comment by jeroenooms** [comment]
Also, does the 500 come with any particular error in the body of the response?

**Comment by JackStat** [comment]
I installed blme, dplyr (they each install a lot of other dependencies), and a package that I based after tvscore.  This is the error that I get

<body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 root@localhost and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at 10.1.10.84 Port 80</address>
</body>

**Comment by jeroenooms** [comment]
I'm sorry it's hard for me to figure out what is going on. I've never seen this. It can happen that you need to restart the server after installing new R packages, but after that it should be stable.

Do you have any ec2 instance running that I can look at?

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/opencpu-server/commit/e22e4e87cb3d1a13a0546508950cf39b95dbc1a5.

**Comment by erikriverson** [comment]
@jeroenooms , we just started experiencing this issue at our site today too (running on EC2). Here's all the details I can find. We just noticed this when one of our tests failed. I visited the URL in a browser and get this returned: 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.7 (Ubuntu) Server at XXXXXXXXXXXX Port 80

## Log files

### /var/log/apache2/error.log 

[Thu Jan 15 09:50:19.619979 2015] [:error] [pid 20528] [client 54.86.73.134:521$
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/ocpu-temp/file503011164369': No such file or directory
Traceback:
No traceback available
[Thu Jan 15 09:51:05.221409 2015] [:error] [pid 20530] [client 54.86.73.134:530$
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/ocpu-temp/file5032818a7dc': No such file or directory
Traceback:
No traceback available
[snip, this continues along these lines for quite some time]

## What changed on our server? 

We've been using this server version for a bit without issue. The only packages recently installed were installed the night before this started happening. These were the "maps" package and the "uuid" package. 

## Fix

I see the comment above mine mentions a possible fix. Is that something I can apply to my local install?

Thanks!

**Comment by jeroenooms** [comment]
It should be fixed if you apt get upgrade to the latest build. Which
version of opencpu-server do you have installed?

**Comment by jeroenooms** [comment]
@erikriverson are you still having this problem after updating to the latest `opencpu-server`?

**Comment by erikriverson** [comment]
Have not seen it since update, thank you!
