### ISSUE TITLE
Graphs from ggplot2 do not display themes

### ISSUE THREAD

**Issue by moosilauke18** [jeroenooms/opencpu#135]
I wrote a plot that I send json data to the function to display.  When I then use curl to get the graphic, the font-size was very small. So I wrote a theme in ggplot2 to change the font size.  The theme does not affect the outputted graph.  

```
getPlot <- function(name) {
    data <- GetDBData(name)
    PLOT <- ggplot(data) + ggtitle("This is a test") + 
        geom_bar(aes(reorder(Name, age), age, fill=age), stat=identity, width=.08) + 
        xlab("") + scale_y_continuous(breaks=pretty_breaks(), limits=c(-1,1), oob=rescale_none) +
        scale_fill_gradient(low="red", high="green", limits=c(-1,1), guide=FALSE) + coord_flip() +
        theme(axis.text=element_text(size=22))
    print(PLOT)
}
```

I'm then using this to send data:
`curl -XPOST http://localhost:7352/ocpu/library/backend/R/getPlot -H "Content-Type: application/json" -d '{"name":"Test"}'`

This outputs things like `/ocpu/tmp/x00352e21a9/graphics/1` which I then use curl to save:
`curl -XGET http://localhost:7352/ocpu/tmp/x00352e21a9/graphics/1/png > test.png`

If I run the package directly from the R(no opencpu) it displays with the theme perfectly.  It's only when I use opencpu that the theme fails to display.  I'm guessing this has something to do with how it processes graphics, but is there a way to fix this?

**Comment by jeroenooms** [comment]
Are you sure it's not related to the version of ggplot2 (or other dependencies) that is in use?

**Comment by jeroenooms** [comment]
It's hard for me to debug this problem without an example. OpenCPU uses the evaluate package to capture graphics. Can you try this:


```r
library(evaluate)
out <- evaluate("getPlot(foo)")
print(out)
```

**Comment by moosilauke18** [comment]
So I re installed opencpu and that fixed the issue.  The weird thing is this is from a fresh OS install so I know all the packages were up-to-date.  I had opencpu_1.4.6 installed before and now I have the same.

I had ran a `curl -XGET http://localhost:7352/ocpu/tmp/x0061b61c3e/info/print` and both had the exact same packages installed.

I'm not sure how that fixed it, but it did.

**Comment by jeroenooms** [comment]
Very strange. Let's hope it's solved now :-)
