### ISSUE TITLE
OpenCPU session fails to load after "some" idle time

### ISSUE THREAD

**Issue by mbacou** [jeroenooms/opencpu#136]
Jeroen,
I've started experiencing a new issue on CentOS6 at http://hcapi.harvestchoice.org/ocpu/. The /test/ page and other API requests work well for a while, but after some idle time (that I'm not able to pinpoint) OpenCPU fails to load completely returning a 500 error. The only workaround is to restart apache, and then everything works well again til the next idle period.

The only error messages I could locate in apache logs are of this type:

```
[Wed Mar 04 13:41:54 2015] [error] [client 38.100.141.210] rApache Notice!, referer: \
http://harvestchoice.org/tools/harvestchoice-data-services
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/ocpu-temp/file43d0233d8a69': No such file or directory
Traceback:
No traceback available
```

My OpenCPU configuration is below. I'm not sure how to debug that one and would very much appreciate any help!
Thanks, --Mel.

```json
{
    "enable.api.library": true,
    "enable.api.apps": true,
    "enable.api.bioc": false,
    "enable.api.cran": false,
    "enable.api.gist": false,
    "enable.api.github": false,
    "enable.api.user": false,
    "enable.api.tmp": true,
    "enable.cors" : true,
    "enable.post.code": false,
    "error.showcall": true,
    "gist.cache": 300,
    "github.cache": 86400,
    "cran.cache": 86400,
    "public.url" : "https://public.opencpu.org/ocpu",
    "smtp.server" : "localhost",
    "httpcache.post": 300,
    "httpcache.lib": 86400,
    "httpcache.git": 900,
    "httpcache.gitapi": 120,
    "httpcache.tmp": 86400,
    "httpcache.cran": 86400,
    "httpcache.static": 31536000,
    "httpcache.bioc": 31536000,
    "key.length" : 9,
    "appspaths": "/usr/local/lib/opencpu/apps-library",
    "repos": "http://cran.rstudio.com",
    "rlimit.as": 3e9,
    "rlimit.fsize": 1e9,
    "rlimit.nproc": 20,
    "timelimit.get": 600,
    "timelimit.post": 90,
    "timelimit.webhook": 900,
    "preload": ["hcapi3","data.table","stringr","rgdal","raster"]
}
```

**Comment by jeroenooms** [comment]
Are you running the latest version? A while ago a bug was fixed that could delete the temporary directory if it was empty. See https://github.com/jeroenooms/opencpu/issues/128.

**Comment by mbacou** [comment]
Hi,
I last built OpenCPU on Dec 29, 2014 using your instructions at https://github.com/jeroenooms/opencpu-server/blob/master/rpm/buildscript.sh
Do I need to reiterate?
Thx a lot, --Mel.

**Comment by jeroenooms** [comment]
Yes, the problem will disappear if you rebuild. You can also fix it manually by editing the `/usr/lib/opencpu/scripts/cleanocpu.sh` script and adding `-mindepth 1` to the lines as in thix [fix](https://github.com/jeroenooms/opencpu-server/commit/e22e4e87cb3d1a13a0546508950cf39b95dbc1a5).

**Comment by mbacou** [comment]
OK thanks. I just rebuilt using the latest sources (didn't see your last comment), and I do see the `-mindepth 1` flags. Will close this issue if the problem goes away.

**Comment by jeroenooms** [comment]
Cool, sorry for the inconvenience. The system working for you otherwise?

**Comment by mbacou** [comment]
Closing this issue. Updating OpenCPU seems to work.

Jeroen, yes OpenCPU is working for us so far. We have one data-heavy API serving/summarizing over 700 spatial indicators that would be difficult to port outside of R. Only thing is we haven't load-tested the server yet, and we're not caching requests using Nginx (a bit worried to have apache and Nginx on the same CentOS6 server), we might look at caching on another server, if that's feasible.
