### ISSUE TITLE
False hits in cache server

### ISSUE THREAD

**Issue by followtheart** [jeroenooms/opencpu#144]
when submit parameters many times with different value using HTTP POST METHOD to same Endpoint,the server return the result generated in first submit and CACHED in server's cache!

Any configuration to disable that shit cache?
Or custom server's cache rule?

**Comment by jeroenooms** [comment]
Are you using the `opencpu-cache` server? Can you give an example of two of those calls that generate a false hit?

**Comment by followtheart** [comment]
We have a API(name it: `FalseHitApi`) on opencpu-server,which show a table with only one record:(0,1,1) in some postgresql server.

First,We call `FalseHitApi` gotten (0,1,1);

Then, we call some other api,change that record (0,1,1) in postgresql to (0,0,0);

At last,we call `FalseHitApi` again,we gotten (0,1,1) from `opencpu-cache`,which should be (0,0,0)

Does this a False hit?

Any way to avoid this？Or disable cache？It seems opencpu-cache `DO NOT` detect changes in third-party data provider.

**Comment by jeroenooms** [comment]
So you are calling opencpu repeatedly with exactly the same http parameters, or are those changing as well? 

Yes you can simply uninstall the cache server, or you can set a `cache-control` request header in your request (analogous to pressing CTRL+R in the browser)
