### ISSUE TITLE
plot svg/png (encoding?) problem with title

### ISSUE THREAD

**Issue by parisni** [jeroenooms/opencpu#146]
Hey,

I have a problem with (only) title that all appears as rectangle characters. My R version is : 
<code>
> Sys.getlocale()
[1] "LC_CTYPE=fr_FR.UTF-8;LC_NUMERIC=C;LC_TIME=fr_FR.UTF-8;LC_COLLATE=fr_FR.UTF-8;LC_MONETARY=fr_FR.UTF-8;LC_MESSAGES=fr_FR.UTF-8;LC_PAPER=fr_FR.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=fr_FR.UTF-8;LC_IDENTIFICATION=C"
</code>

My ocpu version is : 

<code>
X-ocpu-time: 2015-05-27 16:22:38 CEST
Date: Wed, 27 May 2015 14:22:38 GMT
Content-Encoding: gzip
X-ocpu-r: R version 3.2.0 (2015-04-16)
X-ocpu-version: 1.4.7
X-ocpu-server: rApache
Content-Length: 338
Server: Apache/2.4.7 (Ubuntu)
X-ocpu-locale: en_US.UTF-8
Vary: Accept-Encoding
Content-Type: text/plain; charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, X-ocpu-session, Content-Type, Cache-Control
Cache-Control: max-age=86400, public
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, Content-Type, Accept, Accept-Encoding, Cache-Control, Authorization
</code>

I have try to change locale to US in my plot function, this still does not work.

<code>
Sys.setlocale(category = "LC_ALL", locale = "English_United States.1252")
</code>

Are they a config to change the X-ocpu-locale in rApache or something ?

Thanks !

**Comment by jeroenooms** [comment]
Are you sure this is an encoding problem? You could try adding 

```r
Sys.setlocale(category = "LC_ALL", "en_US.UTF-8")
```

to `/etc/opencpu/Rprofile`

**Comment by parisni** [comment]
Updating Rprofile does not help.
I am not sure because the pdf file is ok. 
This is the info/print of the png plot result

<code>
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=en_US.UTF-8    
 [4] LC_COLLATE=en_US.UTF-8  LC_MONETARY=en_US.UTF-8 LC_MESSAGES=C          
 [7] LC_PAPER=C              LC_NAME=C               LC_ADDRESS=C           
[10] LC_TELEPHONE=C          LC_MEASUREMENT=C        LC_IDENTIFICATION=C    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Pubmed4URCPO_0.1 opencpu_1.4.7   

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.5        lattice_0.20-31    grid_3.2.0         jsonlite_0.9.16   
 [5] formatR_1.1        RAppArmor_1.0.1.99 evaluate_0.6       httr_0.6.1        
 [9] brew_1.0-6         unixtools_0.1-1    devtools_1.7.0     tools_3.2.0       
[13] stringr_0.6.2      httpuv_1.3.2       parallel_3.2.0     sendmailR_1.2-1   
[17] base64enc_0.1-2    openssl_0.3        knitr_1.9         
</code>

Here is the R sourcecode :

<code> 
data(cars)
hist(cars$speed)
</code>

**Comment by jeroenooms** [comment]
So what exactly is the problem? What does the output look like?

**Comment by parisni** [comment]
I have got this kind of result http://hpics.li/a673043

**Comment by jeroenooms** [comment]
That usually indicates a missing or misconfigured font.

**Comment by jeroenooms** [comment]
Maybe it's a security problem. Can you look in `/var/log/kern.log` for `DENIED` lines when rendering your plot?

**Comment by parisni** [comment]
<code>
May 27 13:46:34 ubuntu-laptop kernel: [44462.625836] type=1400 audit(1432727194.900:50): apparmor="DENIED" operation="open" profile="opencpu-main" name="/usr/local/texlive/2014/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf" pid=24909 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
</code>

**Comment by parisni** [comment]
Strange as this file has read access for all -rw-r--r--

**Comment by jeroenooms** [comment]
Yes this is apparmor. Add the following line in `/etc/apparmor.d/opencpu.d/custom`:

```
/usr/local/texlive/** rmix,
```

**Comment by jeroenooms** [comment]
Why is it in `/ur/local/`? Did you manually build texlive on this box?

**Comment by parisni** [comment]
Thanks a lot.

I can't remember absolutly but I guess I have installed it from this https://github.com/scottkosty/install-tl-ubuntu

**Comment by jeroenooms** [comment]
You should probably just `apt-get install texlive` next time.

**Comment by parisni** [comment]
debian repos were very late (texlive 2013), that's why i did that. Anyway thanks, opencpu deals with many technology, a way to learn

**Comment by jeroenooms** [comment]
Okay. Did modifying the apparmor profile fix the problem?

**Comment by parisni** [comment]
For sure ! 
<code>
sudo *service* apparmor restart
</code>

**Comment by jeroenooms** [comment]
Oops :)
