### ISSUE TITLE
automatic method redirect oddly broken

### ISSUE THREAD

**Issue by rubenarslan** [jeroenooms/opencpu#147]
I always put [this](https://github.com/rubenarslan/formr.org/issues/134) down to some oddity with our initial machine, but since we've now installed a new machine from scratch and the same problem recurs, I looked into it.
In most cases due to the long session keys, but I haven't exactly figured where in the openCPU code it is redirected and truncated.
If I dial it down a notch from `"key.length" : 70` to 50, it works for my purposes. 
But since the same problem also occurs if you use a long object name, it's probably worth fixing. 

Namely, openCPU usually redirects you to some default format when you call an object without a format, e.g. 
/ocpu/tmp/x000c71946cb567cf753510b356d9741e78f2b6ae09951779a38c0b6ff4365a921e6bf88/console
would redirect to
[..]/console/print

instead it redirects to
[..]/consol

similarly
[..]/info/

redirects to
[..]/info/p

instead of
[..]/info/print/

and 
/ocpu/tmp/x01a893acbad85f3c1b0438a44243c53accfd836f56228feff49/R/verylongobjectnametoillustrateissuetojeroen/

redirects to
[...]/verylongobjectnametoillu

(but x01a893acbad85f3c1b0438a44243c53accfd836f56228feff49/R/verylongobjectnametoillustrateissuetojeroen/print etc. work) 

This is also the problem behind the [redirect loops](https://github.com/jeroenooms/opencpu/issues/121) that I had filed an issue about earlier, namely it happens when the string precisely hits the sweet spot of 90 characters where the truncated path with the method is again the original path, e.g.
/ocpu/tmp/x08709e7aef6882945954f4efb18db64b3ff574c375d05542850/R/verylongobjectnametoillu/

If you want, I can make reproducible examples on the public server using the long object name fault line, but I assume it's clear?

**Comment by rubenarslan** [comment]
Found it, you're [truncating long headers](https://github.com/jeroenooms/opencpu/blob/d007f0b35650f39c66e3f813fddfa50fda59de1c/R/res.R#L31) (>100) and Location is a header.

You probably have a good reason for this which I can't divine, so I won't submit a PR.

**Comment by jeroenooms** [comment]
Mmm i don't remember. Does the http spec or apache2 limit the length?

**Comment by rubenarslan** [comment]
The lowest effective limit for openCPU is probably be the one set by nginx, the pagesize (Apache's is twice that). The limit is not in the spec though.
https://stackoverflow.com/questions/686217/maximum-on-http-header-values

> opencpu:~$ getconf PAGESIZE
4096

So, 4096 bytes. Most openCPU URLs will be ASCII, so as many characters, but even assuming multibyte, you could make the limit 1024, which should be enough even with my bombastically long sessions and obj names. But if you truncate, you should ensure you don't do an infinite loop.

**Comment by rubenarslan** [comment]
Or make it configurable? Also, I think the substring and length methods you use aren't multibyte-safe, but I can't make it break in my testing right now, so I might be wrong.

**Comment by jeroenooms** [comment]
Lets just raise it to something more sensible.
