### ISSUE TITLE
Calling function for JSON return is generating tmp object

### ISSUE THREAD

**Issue by jdanielnd** [jeroenooms/opencpu#151]
I'm not sure if this is an expected behaviour or maybe I'm doing something wrong. But I couldn't find any docs about the temp objects behaviour, so forgive me if my question doesn't make sense.

I'm making the following request:

    POST /ocpu/library/somepackage/R/somefunction/json HTTP/1.1

I don't need to store it as a temporary object since the JSON return contains everything I need. I'm making a lot of this calls. For each of these calls, a temporary object is being created in `/tmp/opencpu-www-data/` and after some hours, the disk is full.

Is this something expected? Is there an option to not save the results in temporary objects?

**Comment by jeroenooms** [comment]
Yes this is expected. One easy fix is to decrease the life time of temp objects in the `/usr/lib/opencpu/scripts/cleanocpu.sh` script. This script gets called from `/etc/cron.d/opencpu`.

**Comment by jdanielnd** [comment]
Ah, nice @jeroenooms! Thanks!

**Comment by jdanielnd** [comment]
@jeroenooms what is the difference between `/tmp/ocpu-temp` and `/tmp/ocpu-www-data/tmp_library`?

**Comment by jeroenooms** [comment]
The `/tmp/ocpu-temp` contains temporary files used by the opencpu system. You can ignore that. The  `/tmp/ocpu-www-data/tmp_library` directory has the actual temporary sessions from `/ocpu/tmp/`.
