### ISSUE TITLE
externalize the DB connexion parameters

### ISSUE THREAD

**Issue by sabrineZhr** [jeroenooms/opencpu#153]
I'm trying to externalize the DB connexion parameters so I thought of using xml file, but I can't find where to put it in opencpu project.

<img width="1176" alt="capture d ecran 2015-07-14 a 19 00 18" src="https://cloud.githubusercontent.com/assets/8748817/8680716/0ccedb46-2a5b-11e5-8576-32c914f9a55b.png">

Any help?
Thank you !

**Comment by moosilauke18** [comment]
Check out hadley's description of `data`: [here](http://r-pkgs.had.co.nz/data.html) on where to store data in an R project.

**Comment by sabrineZhr** [comment]
thank you I put my conf.xml in /extdata but I have the same error 
<img width="536" alt="capture d ecran 2015-07-14 a 20 49 44" src="https://cloud.githubusercontent.com/assets/8748817/8683363/45315c2a-2a6a-11e5-91ef-7609b90fd750.png">

**Comment by moosilauke18** [comment]
You have to put it in `inst/extdata` in the R package.

**Comment by sabrineZhr** [comment]
that's what I did

**Comment by sabrineZhr** [comment]
in parseXMLTree what's the path that I should write ?

**Comment by jeroenooms** [comment]
Try `system.file("extdata/conf.xml", package="yourpkg")`

**Comment by sabrineZhr** [comment]
thank you a lot :D it works. I did xml <- parseXMLTree(system.file("extdata/conf.xml", package="Statistics")
