### ISSUE TITLE
rpc call to R function is not responding in case of OpenCPU cloud server, although it is working fine in single user server

### ISSUE THREAD

**Issue by manusharat** [jeroenooms/opencpu#155]
0 down vote favorite
1
	

I am using OpenCPU for my R project web interface. the project is working fine and i'm able to get results as expected on my local machine (single user server).

then I deployed my project on VM and it didn't work. On VMs the R functions are working properly from R prompt. The single user is also working and i'm able to query it using cURL. but the public server always hangs-up and time-out after 90 secs

other points to note:

    sample projects like tvscore and gitstats are working fine on cloud server as well
    my project is based on rJava. I have had trouble setting it up but finally it worked on single user server.
    I have tried AWS EC2 t2.micro. I have also tried Google n1 (1-CPU 3.75 GB) and n2 (2-CPU 7.5 GB) instances.
    I didn't change anything in my /etc/opencpu/server.conf

the error that I'm getting on failure:

R call did not return within 90 seconds. Terminating process.

my server.conf

{
    "enable.api.library": true,
    "enable.api.apps": true,
    "enable.api.bioc": true,
    "enable.api.cran": true,
    "enable.api.gist": true,
    "enable.api.github": true,
    "enable.api.user": true,
    "enable.api.tmp": true,
    "enable.cors" : true,
    "enable.post.code": true,
    "error.showcall": true,
    "gist.cache": 300,
    "github.cache": 86400,
    "cran.cache": 86400,
    "public.url" : "https://public.opencpu.org/ocpu",
    "smtp.server" : "localhost",
    "httpcache.post": 300,
    "httpcache.lib": 86400,
    "httpcache.git": 900,
    "httpcache.gitapi": 120,
    "httpcache.tmp": 86400,
    "httpcache.cran": 86400,
    "httpcache.static": 31536000,
    "httpcache.bioc": 31536000,
    "key.length" : 9,
    "appspaths": "/usr/local/lib/opencpu/apps-library",
    "repos": "http://cran.rstudio.com",
    "rlimit.as": 2e9,
    "rlimit.fsize": 1e8,
    "rlimit.nproc": 50,
    "timelimit.get": 600,
    "timelimit.post": 90,
    "timelimit.webhook": 900,
    "preload": ["ggplot2", "lattice"]
}

**Comment by jeroenooms** [comment]
Yes there is a [known issue](https://github.com/jeroenooms/opencpu/issues/123) with rJava unfortunately. What do you need Java for?

**Comment by manusharat** [comment]
it is required for my input file generation, and I have no substitute of it. One of the library "rcdk" is depend on it. I want to resolve this issue. to make my predictive app run successfully

**Comment by jeroenooms** [comment]
One way to circumvent the issue is by postponing the loading of the JVM until it is actually needed (rather then when loading your package). So that means instead of importing rcdk in your namespace, you call it in your code using `getFromNamespace` or `rcdk::whatever`

**Comment by manusharat** [comment]
it works, thanks alot for quick and accurate help. And congrats for your amazing tool. 
this solution is creating the response slow, but thank god it start working.

thank you very much.

**Comment by jeroenooms** [comment]
Yes I'm sorry for this limitation. I've been looking into solutions but Java and R just don't play very nice together :(
