### ISSUE TITLE
preventing access to source/console but allow access to files

### ISSUE THREAD

**Issue by rubenarslan** [jeroenooms/opencpu#157]
We use openCPU to generate rmarkdown-feedback via our client app. Usually the user never sees opencpu, because we 
1. use long secret keys to store the result
2. don't hotlink any content from openCPU

We're thinking about switching to hotlinking eg. feedback graphics to shave some time off the feedback generation process. Unfortunately this would give users the secret key. Using that key, they'd be able to look up the code we used to generate the feedback. Sometimes such code can contain sensitive information.

So, now we're looking into preventing access to source/console/stdout. 

We considered

1. a flag in openCPU that prevents storage of the source/console/stdout and just saves the result  
    I'm guessing this does not exist yet and probably our usecase is too rare
2. altering the apache conf to deny access to URLs containing source/console/stdout, via mod_rewrite (maybe with an exception for our client).  
    Seems a bit messy though.

WWJD?

**Comment by jeroenooms** [comment]
People have done nginx proxies to only allow a limited set of urls and methods that you want to expose. This is relatively easy to configure in nginx. I think I would go with that.

**Comment by rubenarslan** [comment]
Thanks for the advice!
We added this to /etc/nginx/opencpu.d/ocpu.conf

```nginx
location ~* /ocpu/tmp/.+?/(messages|source|console|stdout|info|files/.+\.Rmd) {
        allow 134.76.136.64;
        deny all;
        proxy_pass  http://ocpu;
        include /etc/nginx/opencpu.d/cache.conf;
}
```

and commented in `Requires local` in /etc/apache2/sites-available/opencpu.conf

One thing that stumped us for a bit was that ocpu uses the directive `proxy_pass http://ocpu/ocpu` but this does not work with regular expressions in the location parameter for some reason (performance?!). Removing the `/ocpu` for the specific locations did the trick.
