### ISSUE TITLE
ocpu/github/RPackage installs dependencies by default

### ISSUE THREAD

**Issue by JackStat** [jeroenooms/opencpu#159]
It looks like the code in github_install is meant to set dependencies = FALSE but it is specified as upgrade_dependencies and may not be recognized by devtools::install_github

**Comment by jeroenooms** [comment]
No, it is deliberately meant to use the `upgrade_dependencies` parameter introduced in the latest devtools: https://github.com/hadley/devtools/issues/863

**Comment by JackStat** [comment]
aah, I see.  In the meantime dependencies are installed right?  Is there a way to specify that you don't want them installed in the url?

**Comment by jeroenooms** [comment]
Yes the default installs dependencies only when they are needed and not yet installed.

**Comment by JackStat** [comment]
Thank Jeroen.  Sorry for the confusion
