### ISSUE TITLE
Preloading of packages. What am I doing wrong?

### ISSUE THREAD

**Issue by alliquot** [jeroenooms/opencpu#164]
Dear Jeroen,

Let's assume I have a set of libraries to be loaded every time:

    library(DBI)
    library(rmarkdown)
    library(knitr)
    library(stringr)
    library(Kmisc)

So (as root) I modified the **/etc/opencpu/server.conf** file:

    .........
        "preload": ["DBI", "rmarkdown", "knitr", "stringr", "Kmisc"]
    }

Then restated the server:

    service opencpu restart

...and removed these "library(...)" from my R files.

Now, when I call the service, it says: *R returned an error: could not find function "htmlTable"*
When I provide library(Kmisc) - it passes well. The same goes for DBI::dbConnect and so on. It cannot find an object as if corresponding library wasn't (pre)

loaded.

Where is my fault?

**Comment by jeroenooms** [comment]
Are there any messages in `/var/log/opencpu/error.log` or /var/log/apache/error.log` ? Can you navigate to `http://yourserver/ocpu/info` and show the output?

**Comment by jeroenooms** [comment]
I think you are confused between loading and attaching a package. The packages get loaded in memory, but their namespaces do not get attached yet.

In your own package you need to **import** the functions from the other package via your `NAMESPACE` file using e.g:

```
importFrom(Kmisc, htmlTable)
```

Or alternatively you need to call external functions explicitly via `Kmisc:: htmlTable(...)`.

**Comment by alliquot** [comment]
Of course! Facepalm... "My brain hurts" today...
Thank you. It works now.
