### ISSUE TITLE
Select local folder to do list.files and then upload the list of files

### ISSUE THREAD

**Issue by aradius** [jeroenooms/opencpu#167]
I understand how obtain list.files from the local host but I search to import data from a list of files in an user selected folder.
Is it possible?
Thanks

**Comment by jeroenooms** [comment]
?

**Comment by aradius** [comment]
:D
Ok sorry.
I just want to have the folder path (ex on mac OS X: /Users/aradius/Documents/) and then I will apply R function with it.
Is it better?

**Comment by jeroenooms** [comment]
You mean `setwd` / `getwd` ?

**Comment by aradius** [comment]
Yes

**Comment by aradius** [comment]
Like our tv app where you select and load a csv file. I just want to could select a path and doing some R stuff with it likes list.files() etc.
Thanks for your patience

**Comment by aradius** [comment]
Ok this is not possible for now. I need to upload all the files via curl and do R stuff on it.
