### ISSUE TITLE
curl.so: undefined symbol: MD5_Init

### ISSUE THREAD

**Issue by SarumObjects** [jeroenooms/opencpu#173]
I am trying to install opencpu on RHEL6 and as part of that I need to install 'curl' from CRAN.
Whatever I do (including various libcurl/openssl combinations) I cannot satisfy this symbol.
(No problems on Centos 7 - but that's not my production machine)
Any clues would be welcome.

**Comment by jeroenooms** [comment]
It helps if you include more output. Can you show me the full install log? Also can you post the output of these commands:

```
pkg-config --cflags libcurl
pkg-config --libs libcurl
pkg-config --libs --static -libcurl
```

**Comment by SarumObjects** [comment]
Hi

[baysient@499403-db1 R-3.2.3]$ pkg-config --cflags libcurl

[baysient@499403-db1 R-3.2.3]$ pkg-config --libs libcurl

-lcurl  

[baysient@499403-db1 R-3.2.3]$ pkg-config --libs --static -libcurl

-libcurl: unknown option

 

[baysient@499403-db1 R-3.2.3]$ ./bin/R CMD INSTALL curl

* installing to library â/home/baysient/Downloads/R-3.2.3/libraryâ

* installing *source* package âcurlâ ...

Found pkg-config cflags and libs!

Using PKG_CFLAGS= 

Using PKG_LIBS=-lcurl  

** libs

make: Nothing to be done for `all'.

installing to /home/baysient/Downloads/R-3.2.3/library/curl/libs

** R

** data

*** moving datasets to lazyload DB

** preparing package for lazy loading

** help

*** installing help indices

** building package indices

** installing vignettes

** testing if installed package can be loaded

Error in dyn.load(file, DLLpath = DLLpath, ...) : 

  unable to load shared object '/home/baysient/Downloads/R-3.2.3/library/curl/libs/curl.so':

  /home/baysient/Downloads/R-3.2.3/library/curl/libs/curl.so: undefined symbol: MD5_Init

Error: loading failed

Execution halted

ERROR: loading failed

* removing â/home/baysient/Downloads/R-3.2.3/library/curlâ

[baysient@499403-db1 R-3.2.3]$

 

John

**Comment by jeroenooms** [comment]
It looks as if you don't have a proper curl library. Can you try `sudo yum install libcurl-devel` ?

**Comment by SarumObjects** [comment]
It is installed already:: that’s the confusing part: I even have compiled curl & openssl1.01q from source.

 

baysient@499403-db1 R-3.2.3]$ sudo yum install libcurl-devel

[sudo] password for baysient: 

Loaded plugins: product-id, rhnplugin, security, subscription-manager

This system is receiving updates from RHN Classic or RHN Satellite.

Setting up Install Process

epel/metalink                                                                                                                                                                   |  13 kB     00:00     

jenkins                                                                                                                                                                         |  951 B     00:00     

mongodb                                                                                                                                                                         |  951 B     00:00     

rackspace-rhel-x86_64-server-6-common                                                                                                                                           |  871 B     00:00     

rhel-x86_64-server-6                                                                                                                                                            | 1.5 kB     00:00     

rhel-x86_64-server-optional-6                                                                                                                                                   | 1.5 kB     00:00     

rhn-tools-rhel-x86_64-server-6                                                                                                                                                  | 1.3 kB     00:00     

Package libcurl-devel-7.19.7-46.el6.x86_64 already installed and latest version

Nothing to do

[baysient@499403-db1 R-3.2.3]$

**Comment by jeroenooms** [comment]
You shouldn't install form source, you should stick with the repository version. I think the problem is that you didn't build/install your local version properly. I am guessing you only built the static library (`libcurl.a`) but we need the (`libcurl.so`). Maybe you can try this:

```
wget https://cran.r-project.org/src/contrib/curl_0.9.5.tar.gz
R CMD INSTALL curl curl_0.9.5.tar.gz --configure-vars='INCLUDE_DIR=/usr/include LIB_DIR=/usr/lib'
```

**Comment by jeroenooms** [comment]
ps please try to post replies via the github webpage rather than via email

**Comment by SarumObjects** [comment]
I reinstalled libcurl-devel and tried a number of combinations starting from your suggesting (including this one which located the re-installed libcurl.so - but still the same:
```
 R CMD INSTALL  curl --configure-vars='INCLUDE_DIR=/usr/local/include LIB_DIR=/usr/lib64'
* installing to library â/usr/local/lib64/R/libraryâ
* installing *source* package âcurlâ ...
** package âcurlâ successfully unpacked and MD5 sums checked
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/usr/local/include 
Using PKG_LIBS=-L/usr/lib64 -lcurl
** libs
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c callbacks.c -o callbacks.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c curl.c -o curl.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c download.c -o download.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c escape.c -o escape.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c fetch.c -o fetch.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c form.c -o form.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c getdate.c -o getdate.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c handle.c -o handle.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c ieproxy.c -o ieproxy.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c init.c -o init.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c nslookup.c -o nslookup.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c utils.c -o utils.o
gcc -std=gnu99 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/local/include  -I/usr/local/include    -fpic  -g -O2  -c version.c -o version.o
gcc -std=gnu99 -shared -L/usr/local/lib64/R/lib -L/usr/local/lib64 -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o nslookup.o utils.o version.o -L/usr/lib64 -lcurl -L/usr/local/lib64/R/lib -lR
installing to /usr/local/lib64/R/library/curl/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib64/R/library/curl/libs/curl.so':
  /usr/local/lib64/R/library/curl/libs/curl.so: undefined symbol: MD5_Init
Error: loading failed
Execution halted
ERROR: loading failed
* removing â/usr/local/lib64/R/library/curlâ
$ 

````

**Comment by jeroenooms** [comment]
Can you show me the output of ldd?

```
R CMD INSTALL curl_0.9.5.tar.gz --no-test-load --configure-vars='INCLUDE_DIR=/usr/local/include LIB_DIR=/usr/lib64'
cd /usr/local/lib64/R/library/curl/libs/
ldd curl.so
```

**Comment by SarumObjects** [comment]
Thanks for your suggestions. Finally by removing references to /usr/local/lib (by pointing to /usr/lib64) I think I have everything installed and working. This included using
```
R CMD INSTALL --configure-vars="LIBS='-lz -lcrypto -lssl -ldl'" opencpu
```
