### ISSUE TITLE
Differing Behaviour Of Package Using rjulia When Run On Cloud vs Single-User Severs

### ISSUE THREAD

**Issue by adamsardar** [jeroenooms/opencpu#174]
Hi,

First of all - thank you for developing the excellent OpenCPU platform, it really is a great addition to the R ecosystem.

I'm looking for some help. I've written a package in R that makes use of [rjulia](https://github.com/armgong/rjulia) to interface with Julia. Why? I need to use the [JuMP](https://jump.readthedocs.org/en/latest/) integer linear programming library (such as [GLPK](https://www.gnu.org/software/glpk/)) to build particular models and such functionality is not available in pure R. rjulia links directly to julia.so and JuMP then links with libglpk.so.

If I run opencpu as the stand-alone single-user server, the commands work fine. If I deploy this package into production, then things do not work properly. Variables seem to get 'lost' for lack a better description.

I've created a test package with two functions (replicated below); the first (generateRandomNumbersFromJulia) runs as expected on the cloud opencpu server and returns 10 random integers (generated in julia) from between 1 and 10, confirming that the r-julia bridge behaves itself; the second (milpInGLPK) attempts to build a very simple GLPK model in julia, solves it and then print out the variables, which on the single-user server gives ["x: " "4"   "y: " "1"  ]  - as expected - but on the cloud server we get ["x: ", "y: "]. My suspicion is that there is an error in creating the julia model, but that this is swallowed by rjulia and hence we just get null values out of the model. As to why this happens, I cannot figure it out.

The only thing that appears whilst querying the cloud server in /var/log/apache2/error.log is this:
[...]
Checking Apparmor Status...
 AppArmor status lookup failed. Error code: ECANCELED
AppArmor is available on the system but has been disabled at boot
[...]

I appreciate that we have a number of different projects in the mix here and it may well be that it's not opencpu that is the root cause of this strange behaviour, but any insight from your experience with such issues would be very much appreciated.

generateRandomNumbersFromJulia:
```
#' generate 10 random numbers from between 1 and 10
#'
#' @return randNums a vector of ten random numbers from the range 1:10
#' @export
generateRandomNumbersFromJulia <- function(){

  randNums <- rjulia::j2r(" rand(1:10,10)")

  return(randNums)
}
```

milpInGLPK
```
#' Builds a toy MILP and solves it
#'
#' @return solvexy The MILP solver values for x and y
#' @export
milpInGLPK <- function(){

  rjulia::jDo("using JuMP")
  rjulia::jDo("using GLPK")

  prepareModel()

  rjulia::jDo("status = solve(m)")

  rjulia::jDo("gc()")

  solvexy <- c("x: ",rjulia::j2r("getValue(x)"),"y: ",rjulia::j2r("getValue(y)"))

  return(solvexy)
}

prepareModel<-function(){

  rjulia::jDo("m = Model()")
  rjulia::jDo("@defVar(m, x >= 0) ")
  rjulia::jDo("@defVar(m, y >= 0)")
  rjulia::jDo("@setObjective(m, Min, x + y)")
  rjulia::jDo("@addConstraint(m, x + y >= 5)")
  rjulia::jDo("@addConstraint(m, x  >= 3)")
  rjulia::jDo("@addConstraint(m, y  >= 1)")
}
```

n.b. I used the rjulia::jDo style of running commands so as to rule out behaviour such as that seen in [#123](https://github.com/jeroenooms/opencpu/issues/123)

My server.conf is as follows (note, I had to increase rlimit.as since default julia asks for (8GB of RAM on start-up)[https://github.com/JuliaLang/julia/issues/10390] :

{
    "enable.api.library": true,
    "enable.api.apps": true,
    "enable.api.bioc": true,
    "enable.api.cran": true,
    "enable.api.gist": true,
    "enable.api.github": true,
    "enable.api.user": true,
    "enable.api.tmp": true,
    "enable.cors" : true,
    "enable.post.code": true,
    "error.showcall": true,
    "gist.cache": 300,
    "github.cache": 86400,
    "cran.cache": 86400,
    "public.url" : "https://public.opencpu.org/ocpu",
    "smtp.server" : "localhost",
    "httpcache.post": 300,
    "httpcache.lib": 86400,
    "httpcache.git": 900,
    "httpcache.gitapi": 120,
    "httpcache.tmp": 86400,
    "httpcache.cran": 86400,
    "httpcache.static": 31536000,
    "httpcache.bioc": 31536000,
    "key.length" : 9,
    "appspaths": "/usr/local/lib/opencpu/apps-library",
    "repos": "http://cran.rstudio.com",
    "rlimit.as": 10e9,
    "rlimit.fsize": 1e9,
    "rlimit.nproc": 50,
    "timelimit.get": 120,
    "timelimit.post": 2400,
    "timelimit.webhook": 900,
    "preload": []
}

Again - thank you for openCPU!

Adam

**Comment by jeroenooms** [comment]
Hmm yes this might be too complex to reproduce. Can you check if there are any errors in `/var/log/kern.log` on the cloud server?

**Comment by adamsardar** [comment]
So I've fixed the bug, but my do I feel sheepish in explaining what the issue was!

Unlike R, julia doesn't allow you to install packages site-wide by default PLUS it creates a cache in the home directory of the user. All well and fine, until you have a user that has no home such as www-data. The fix is simple enough - enable [site-wide package installs for julia](https://groups.google.com/forum/#!topic/julia-users/9lQZJlLs99M) and set JULIA_PKGDIR="/tmp/.julia/0.4" and HOME="/tmp/" in /etc/opencpu/Renviron.

All of this has almost nothing to do with opencpu! So I'll close this issue here. Thanks again for the software.

(/var/log/kern.log was clean by the way)
