### ISSUE TITLE
Extraneous ".\" in TAR archive file names

### ISSUE THREAD

**Issue by mbacou** [jeroenooms/opencpu#176]
Jeroen,
Just a cosmetic problem I noticed today when using the `/ocpu/tmp/{key}/tar` API. File names in the TAR archive looks like this. 

![image](https://cloud.githubusercontent.com/assets/260325/13383221/97a0b6f6-de54-11e5-8948-c683b8f17944.png)

Also some of the session text files look quite garbled:

![image](https://cloud.githubusercontent.com/assets/260325/13383522/b44b7f80-de58-11e5-9471-f7f83607681f.png)

I'm on CentOS6 but assume it's not related.

Thx, --Mel.

**Comment by jeroenooms** [comment]
This issue does not seem to exist on my Ubuntu 14.04 servers so it is likely related to CentOS6, either `tar` utility is outdated or R has been incorrectly configured for use with that particular version of `tar`. 

OpenCPU [simply calls](https://github.com/jeroenooms/opencpu/blob/master/R/httpget_session_tar.R) `utils::tar()` so I don't have much control over this...

**Comment by mbacou** [comment]
Right, somehow both the zip() and tar() commands have issues on this CentOS6. Will try to debug and post back. Thanks for checking.

**Comment by jeroenooms** [comment]
You might want to upgrade at some point :-) CentOS6 is also increasingly problematic because it doesn't support https due to the outdated libcurl...

**Comment by mbacou** [comment]
Indeed, the main reason for CentOS6 is our hosting provider only offer this option til now (CentOS6, Ubuntu 13.04). We maintain Ubuntu 14.04 servers on AWS to host apps, but don't use AWS for scientific computing. Moving forward would rApache/openCPU/Nginx be fully supported on CentOS7 or better switch to Ubuntu 14?

**Comment by jeroenooms** [comment]
Definitely Ubuntu. Even CentOS7 still has pretty old versions of most libraries; ubuntu stays much more current. Also the fact that Ubuntu includes R in the standard distribution guarantees that everything gets a lot of testing. On CentOS you need to compile R from source or grab a backport from EPEL or so, which don't always work as well, as this issue shows. 

Next month Ubuntu releases the next LTS release, 16.04 (their versions numbers are YY-MM) so this will become the new recommended distribution, although we will keep supporting 14.04 as well for a while.

**Comment by mbacou** [comment]
Okay noted, thanks for the info! Will check with our provider when they plan to roll out 16.04 (hopefully not 3 years from now) (-:
