### ISSUE TITLE
remove dependence on unixtools

### ISSUE THREAD

**Issue by sandys** [jeroenooms/opencpu#185]
hi,
unixtools fails installation on R 3.2.3 
```
> install.packages("unixtools", dependencies=TRUE, repos='http://cran.rstudio.com/')
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Warning message:
package ‘unixtools’ is not available (for R version 3.2.3) 

```
I tried a couple of repos, but it is a no go.

I looked at your code (and also a possibly relevant old question on [stackoverflow](http://stackoverflow.com/questions/17841332/using-install-packages-with-custom-temp-dir/17881157#17881157)) . Can the use of unixtools be replaced by Sys ?

**Comment by jeroenooms** [comment]
This package is included with the opencpu-server library: https://github.com/jeroenooms/opencpu-server/tree/v1.6/opencpu-lib

**Comment by sandys** [comment]
@jeroenooms sorry to bother you on this.... but unixtools has not been updated in two years. 

Is there a way I can fix this for you ? Because unixtools is used in exactly two lines in opencpu. 

`getExportedValue("unixtools", "set.tempdir")(mynewtempdir);`
can probably be replaced by

```
Sys.setenv(TMPDIR=mynewtempdir)
```

Also,
```
homedir <- function(username){
  #easiest method
  home <- path.expand(paste0("~", username));
  if(file.exists(home)){
    return(home);
  }
  
  #second method
  unixtools = "unixtools";
  if(requireNamespace(unixtools, quietly = TRUE)){
    return(getExportedValue(unixtools, "user.info")(username)$home)
  }
  
  #third method
  if(file.exists("/etc/passwd")){
    out <- try(utils::read.table("/etc/passwd", sep=":", row.names=1, as.is=TRUE));
    if(!inherits(out, "try-error") && length(out) && nrow(out)){
      homelib <- out[username, "V6"];
      if(!is.na(homelib) && file.exists(homelib)){
        return(homelib)
      }
    }
  }
  
  stop("Could not find or access home directory of user ", username);
}
```

can probably be replaced with a variant of your own - https://github.com/jeroenooms/gpg/blob/d74f01f69450517250eadefefbd32a0ebf8f7540/R/configdir.R

or with one of
```

Sys.getenv("R_LIBS_USER")
Sys.getenv("R_USER")
Sys.getenv("HOME", unset="~")

```

**Comment by jeroenooms** [comment]
The `set.tempdir` function sets the `C` level global, which is different form the envvar. The environment variable is only used when R is started, there is no point in setting it later on. 

What is the problem with installing unixtools? To install manually either use

```r
install.packages("https://github.com/jeroenooms/opencpu-server/raw/v1.6/opencpu-lib/unixtools_0.1-1.tar.gz", repos = NULL)
```

or

```r
devtools::install_github/s-u/unixtools
```

But again, I really commend using the deb/rpm source package which contains everything you need, and install from that.

**Comment by sandys** [comment]
closing this - have been successful using your older unixtools. The reason I filed this bug was if the library is outdated, perhaps there was a way to achieve it using the currently available libraries.
thanks!
