### ISSUE TITLE
CentOS with httpd24

### ISSUE THREAD

**Issue by mbacou** [jeroenooms/opencpu#188]
Jeroen,
I'm running into the usual issue on CentOS 6.7 with rapache built against apache 2.4. `opencpu-lib-*.rpm` installs no problem, but `opencpu-server-*.rpm` is not finding rapache. This is related to https://github.com/jeffreyhorner/rapache/issues/36.

I've tried:

```
$ scl enable httpd24 bash # prepends /opt/rh/httpd24/root/usr/bin:/opt/rh/httpd24/root/usr/sbin: to $PATH
$ sudo scl enable httpd24 'rpmbuild -ba ~/rpmbuild/SPECS/opencpu.spec'
$ sudo scl enable httpd24 'rpm -U opencpu-server-*.rpm'
error: Failed dependencies:
        rapache is needed by opencpu-server-1.6.1-rpm0.x86_64
```

Is there a quick workaround? Embarrassed to say I forgot the steps I followed last time!
Thanks, --Mel.

**Comment by jeroenooms** [comment]
It looks like forgot to [build](https://github.com/jeroenooms/opencpu-server/blob/v1.6/rpm/buildscript.sh#L19-L22) and [install](https://github.com/jeroenooms/opencpu-server/blob/v1.6/rpm/buildscript.sh#L39) rapache?

**Comment by mbacou** [comment]
I had to manually source built the rapache libs and install at `/opt/rh/httpd24/root/usr/lib` on CentOS. Using `--nodeps` flag to install opencpu-server was ok then.

```
$ sudo rpm -Uvh --nodeps opencpu-server-*.rpm
```
