### ISSUE TITLE
restart opencpu server (service) automatically

### ISSUE THREAD

**Issue by KrishnaPG** [jeroenooms/opencpu#192]
After a reboot the opencpu service is not starting automatically. Does it require some special configuration?

This is what it is showing for status on a Ubuntu 16 VM (on Azure) after reboot:

````
ocpu-test:~$ sudo service opencpu status
● opencpu.service - OpenCPU Server
   Loaded: loaded (/etc/systemd/system/opencpu.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
````

Also,

> What happens if (for any reason) the OpenCPU service crashes? Does it respawn automatically (something like supervisord etc.)? If not, how to enable it?

**Comment by KrishnaPG** [comment]
This command helps:
````
sudo systemctl enable opencpu.service
````

**Comment by frankyan** [comment]
How can I restart and automatically restart opencpu-server service on CentOS? It doesn't work.

```
[root@centos ~]# sudo service opencpu restart
Redirecting to /bin/systemctl restart  opencpu.service
Failed to restart opencpu.service: Unit not found.
```

```
[root@centos ~]# sudo systemctl enable opencpu.service
Failed to execute operation: No such file or directory
```

**Comment by jeroen** [comment]
This has changed in OpenCPU 2.0. You now just need to restart apache:

```
sudo apachectl restart
```
