### ISSUE TITLE
Right way to handle the tmp / output files / location / space ?

### ISSUE THREAD

**Issue by KrishnaPG** [jeroenooms/opencpu#194]
Each method invocation is resulting around 5 to 6 files at a minimum, and soon the `/tmp` will be flooded with numerous small files that may  or not may not be really needed.

What is the right way to deal with this situation? Any recommended strategy that others are following successfully?

The problematic scenarios are:

- How to reclaim the `/tmp` space automatically when outputs have life-time. For example, all outputs more than 30 days old to be purged automatically
- In case every output generated is important and need to be retained, how to reconfigure the `/tmp` to use something like S3 storage or some other cloud storage?
- Is it possible to have them `/tmp` files be stored in compressed format? Apache already has the capability to serve compressed content (that browsers can decompress on the fly automatically)

**Comment by jeroenooms** [comment]
The standard installation has a cron job which runs this script every 10 minutes: https://github.com/jeroenooms/opencpu-server/blob/v1.6/opencpu-server/scripts/cleanocpu.sh

**Comment by KrishnaPG** [comment]
Thank you. In the script, there are two folder mentioned `/tmp/ocpu-temp/ ` and `/tmp/ocpu-www-data/tmp_library/` Wondering what is the purpose of each. 

The `/tmp/ocpu-temp/` looked like contained only text files (output?) The `/tmp/ocpu-www-data/tmp_library/` what does it contain? Some of the folders inside it contained only `DESCRIPTION` that all looked same with below content
````
Package: x01d36d467b
Type: Session
Version: 1.0
Author: OpenCPU
Date: 2016-07-31
Description: This file is automatically generated by OpenCPU.
````

**Comment by jeroenooms** [comment]
The `/tmp/ocpu-www-data/tmp_library/` directory contains the temporary session store, i.e. what is available via `/ocpu/tmp` in the API. By default these are cleaned after 24 hours.

The `/tmp/ocpu-temp/` contains temporary files used by R, i.e. when you use `tempfile()` in R. These are not needed after the session end and get trashed every 15 min.

**Comment by KrishnaPG** [comment]
Thank you. That info is helpful.
