### ISSUE TITLE
GET function code not updating

### ISSUE THREAD

**Issue by emi-silva** [jeroenooms/opencpu#195]
When I change a function and then I GET the function code through the API, it doesn't update.

1. In RStudio server, create a new package.
2. Build & Reload the package
3. In the API Explorer, GET the default function, hello. You get the result
```
function() {
  print("Hello, world!")
}
```
4. In RStudio server, edit the hello.R script. Write "champion" instead of "world".
5. Build & Reload
6. In the API Explorer GET hello again. You still get
```
function() {
  print("Hello, world!")
}
```

**Comment by r2evans** [comment]
Is it being cached? Check the http headers and/or delete the last hour of cache is your browser and try again.

**Comment by emi-silva** [comment]
Yes, that was it. Thank you!
