### ISSUE TITLE
Is it to possible install R packages via opecpu apis?

### ISSUE THREAD

**Issue by iwidanalage** [jeroenooms/opencpu#196]
Is it to possible install R packages via opecpu apis?

Things I tried so for and didn't work

*1. Use identity function *

```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'x=install.packages('aws.signature')' "http://localhost:8004/ocpu/library/base/R/identity/json"

Response
=========
unable to install packages

In call:
install.packages("aws.signature")

```

*2. Use cran API *

```
curl -X GET  "http://localhost:8004/ocpu/cran/aws.signature"

Response
=========
(Takes a while on first time, looks like it installing the package somewhere) Returns the package info
```

However, after this if I do GET http://localhost:8004/ocpu/library/aws.signature, it returns 400 with error
```
there is no package called 'aws.signature'

In call:
find.package(pkgname, lib.loc = lib.loc)
```

**Comment by jeroenooms** [comment]
If your package is on github, you can install packages via the github webhook: https://www.opencpu.org/api.html#api-ci

**Comment by iwidanalage** [comment]
Thanks for the reply. What I was looking for is an API to install cran packages.
