### ISSUE TITLE
Opencpu 1.5.3 > How to set specific  R_Home 

### ISSUE THREAD

**Issue by capiisco** [jeroenooms/opencpu#199]
Hi.

I have several R version on my machine (...  3.2.0,3.2.1,3.2.2). 
How to tell opencpu to use the one or the other version. Specify it in the opencpu Renviron file doesn't work. My wish is to configure opencpu with a version which is in a specific location

Best Regards

**Comment by jeroenooms** [comment]
Which OS is this? How did you install multiple versions of R?

**Comment by capiisco** [comment]
Red Hat Enterprise Linux VERSION=7.0 . It's the mutualized machine , that accommodates several applications which uses specific versions of R. A choice which had been made for isolated the R versions of applications, and not to undergo the impact of regression further to an update of the R version  by default

**Comment by jeroenooms** [comment]
So you installed the opencpu server and rapache via the rpm package? In this case the path of R gets hardcoded when building rapache I think.

**Comment by capiisco** [comment]
Yes I used rpm packages for install. 
So, to configure a specific R version, I have to install Rapache manually with the option - with-R =/path/to/R (To select a specific path of R) ?

yum install –y opencpu-lib-1.5.3-rpm0.x86_64.rpm rapache-1.2.7-rpm0.x86_64.rpm opencpu-server-1.5.3-rpm0.x86_64.rpm rapache-debuginfo-1.2.7-rpm0.x86_64.rpm

**Comment by jeroenooms** [comment]
You can either install rapache manually or edit the `configure` line from the `rapache.spec` and try rebuild the rpm: https://github.com/jeffreyhorner/rapache/blob/master/rpm/rapache.spec#L26

**Comment by capiisco** [comment]
Thx for information. I will try to rebuild rmp.
