### ISSUE TITLE
http://mywebsite.com/ocpu 404 Not Found

### ISSUE THREAD

**Issue by alena-zhuk** [jeroenooms/opencpu#202]
Hello,

I've installed OpenCPU cloud server on Ubuntu Server 16.04 LTS hosted in Azure Cloud. However I receive 404 status when trying to access the opencpu welcome page (/ocpu).  
OpenCPU error log doesn't contain any errors and the service seems to be running. 
![image](https://cloud.githubusercontent.com/assets/18050659/18919934/2cb00bd2-85a0-11e6-99d0-06a35f1f82ca.png)
I noticed hostname guess shows unavailable host. But after some research i figured out that hostname guess tries to get the address by ec2 metadata, which returns "unavalable". And this should not affect the functionality.
Apache2 is running and working well.
/var/log/opencpu/apache_error.log is empty. 
Could you please point me what could be misconfigured?

**Comment by SinanGabel** [comment]
Hi!

I believe you can add the below, and then restart Apache (PS to check
config first do: "apachectl -t"):

Add at the end of `/etc/apache2/apache2.conf`
ServerName localhost

**Comment by alena-zhuk** [comment]
Hi!
Thank you for your help! 
I've set ServerName, but it hasn't fixed my problem.  
The actual problem was in rapache, since it failed to install and i missed the warnings.
 
`W: The repository 'http://ppa.launchpad.net/opencpu/rapache/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/opencpu/rapache/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.`

I've build the package from source and installed it. And now i finally see the page!
