### ISSUE TITLE
Ubuntu 16.04 install fails

### ISSUE THREAD

**Issue by richshaw** [jeroenooms/opencpu#204]
Hi, I've been working on getting OpenCPU installed, but I had a few problems.

I boot up a fresh instance of Ubuntu 16.04 and run the following:

``` bash
apt-get install software-properties-common
sudo add-apt-repository -y ppa:opencpu/opencpu-1.6
sudo apt-get update 
sudo apt-get upgrade

sudo apt-get install -y opencpu
```

Install script starts running but fails towards the end...

``` bash
installing opencpu init script.
insserv: Service apache2 has to be enabled to start service opencpu
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package opencpu-server (--configure):
subprocess installed post-installation script returned error exit status 1
```

Full install log available here: [opencpu_install_log.txt](https://drive.google.com/file/d/0B0T6Ohy68eGiOXRnR3hCMFhXZ2s/view?usp=sharing)

**Temporary fix**

I figure the script could be trying to start the opencpu service before apache has started.

With clean Ubuntu instance I install the opencpu dependencies before trying to install opencpu.

``` bash
apt-get install software-properties-common

sudo add-apt-repository -y ppa:marutter/rrutter
sudo apt-get update

apt-key adv --keyserver keyserver.ubuntu.com --recv-key 381BA480
echo "deb http://cran.rstudio.com/bin/linux/debian jessie-cran3/" > /etc/apt/sources.list.d/cran.list

sudo add-apt-repository -y ppa:opencpu/opencpu-1.6

sudo apt-get dist-upgrade -y
sudo apt-get update 
sudo apt-get upgrade

sudo apt-get install -y wget make devscripts apache2-dev apache2 libapreq2-dev r-base r-base-dev libapparmor-dev libcurl4-openssl-dev libprotobuf-dev protobuf-compiler xvfb xauth xfonts-base curl libssl-dev libxml2-dev libicu-dev pkg-config

sudo apt-get install -y opencpu
```

This worked and opencpu is up and running.

**Comment by jeroenooms** [comment]
OK this should be fixed now. The problem was that Ubuntu now contains `libapache2-mod-r-base` in the main repository, but it is slightly different from the one we shipped ourselves.

**Comment by richshaw** [comment]
Awesome, thank you.
