### ISSUE TITLE
Can a session data be retained in memory for faster access later on?

### ISSUE THREAD

**Issue by ttdtrang** [jeroenooms/opencpu#206]
I ran into the need of accessing an OpenCPU call's result repeatedly during a user's working session. The only way I'm aware of is using a session key assigned for the call to retrieve the files corresponding to the session, from disk. Is there a mechanism to allow retaining some of these data in memory for faster access?

**Comment by oliverbock** [comment]
I would say no because you have no guarantee that your next request will go to the same Apache process.

**Comment by ttdtrang** [comment]
Thanks!

**Comment by SinanGabel** [comment]
PS Unless you e.g. make an R script that allows for uploading of user data to a specific database (placed on same server as the R server for fast retrieval, and possibly in-memory), and that the original function uses.
