### ISSUE TITLE
Is it possible to share in-memory data among opencpu/apache processes?

### ISSUE THREAD

**Issue by ttdtrang** [jeroenooms/opencpu#207]
In an attempt to reduce disk IOs upon answering queries from client app, I decided to `preload` a large amount of data in the package, i.e put the data loading in `.onLoad()`, and add `mypackage` into `preload[]` of `/etc/opencpu/server.conf`

It turns out to me that, each apache process has its own copy of the data, and the system memory is quickly exhausted.

Is there any configuration to allow sharing a single read-only object in the memory across all opencpu client app? I'm not sure if this is more related to OpenCPU or Apache, or if it requires deeper modification of the way Apache/OpenCPU works. To me that seems like a very basic need to help serving more requests without greatly scaling up the hardware. As long as the data is read-only, wouldn't it be ok and advisable to share across all instances?

**Comment by jeroenooms** [comment]
Perhaps you could stick your object in a redis server and load it in R via an R-redis client?

**Comment by ttdtrang** [comment]
This is the first time I heard about Redis. That sounds a viable solution. Let me try it out.

**Comment by ttdtrang** [comment]
Solution with redis works well so far. Thanks for the great suggestion! :)
