### ISSUE TITLE
My local user library is empty after fresh install in Ubuntu?

### ISSUE THREAD

**Issue by bravegag** [jeroenooms/opencpu#208]
Hi, I did a fresh OpenCPU install in my local Ubuntu machine and trying to test some packages installed under my user library OpenCPU shows no packages:

	bravegag@zeus:~/code/myproject$ curl -L http://localhost/ocpu/info
	R version 3.3.1 (2016-06-21)
	Platform: x86_64-pc-linux-gnu (64-bit)
	Running under: Ubuntu 14.04.5 LTS

	locale:
	 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=en_US.UTF-8    
	 [4] LC_COLLATE=en_US.UTF-8  LC_MONETARY=en_US.UTF-8 LC_MESSAGES=C          
	 [7] LC_PAPER=C              LC_NAME=C               LC_ADDRESS=C           
	[10] LC_TELEPHONE=C          LC_MEASUREMENT=C        LC_IDENTIFICATION=C    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	other attached packages:
	[1] opencpu_1.6.5

	loaded via a namespace (and not attached):
	 [1] RAppArmor_2.0.2 magrittr_1.5    sendmailR_1.2-1 tools_3.3.1    
	 [5] parallel_3.3.1  base64enc_0.1-3 stringi_1.1.1   grid_3.3.1     
	 [9] stringr_1.1.0   jsonlite_1.0    unixtools_0.1-1 openssl_0.9.4  
	[13] lattice_0.20-33 evaluate_0.9   
	bravegag@zeus:~/code/myproject$ curl -L http://localhost/ocpu/user/bravegag/

	bravegag@zeus:~/code/myproject$ 

But checking using plain r I see the packages listed:

	bravegag@zeus:~/code/myproject$ R

	R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
	Copyright (C) 2016 The R Foundation for Statistical Computing
	Platform: x86_64-pc-linux-gnu (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> installed.packages("/home/bravegag/R/x86_64-pc-linux-gnu-library/3.1")
	               Package         
	bitops         "bitops"        
	brew           "brew"          
	colorspace     "colorspace"    
	crayon         "crayon"        
	curl           "curl"          
	devtools       "devtools"      
	dichromat      "dichromat"     
	digest         "digest"

**Comment by jeroenooms** [comment]
That's not your home library; the directory name is `3.1` and you are running R `3.3`. What do you see if you run in R:

```r
Sys.getenv("R_LIBS_USER")
```

**Comment by bravegag** [comment]
I see this:

	bravegag@zeus:~/code/myproject$ R

	R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
	Copyright (C) 2016 The R Foundation for Statistical Computing
	Platform: x86_64-pc-linux-gnu (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> Sys.getenv("R_LIBS_USER")
	[1] "~/R/x86_64-pc-linux-gnu-library/3.3"

interesting ... what do you do recommend? renaming the directory to be 3.3?

**Comment by jeroenooms** [comment]
No, just reinstall the packages. They will automatically be installed in the correct directory.

**Comment by bravegag** [comment]
OKI thanks will try that!

**Comment by bravegag** [comment]
Yes it works thanks! Although my package is seen now, If I make a request to a  function in my package that generates a plot, it gives back:

    File not found: /home/bravegag/R/x86_64-pc-linux-gnu-library/3.3/myproject/generate_plot_from_json

Why OpenCPU doesn't find my method? or what is wrong with it?

**Comment by jeroenooms** [comment]
The R functions are under `pkg/R/fun` in the API. You are missing the `/R` part.
