### ISSUE TITLE
problem of opencpu working with `xlsx::read.xlsx2` and `xlsx::write.xlsx2`

### ISSUE THREAD

**Issue by slfan2013** [jeroenooms/opencpu#216]
I got a problem with I tried to load xlsx file with `xlsx `package `read.xlsx2` function and write xlsx file with `write.xlsx2` function (It works locally but failed with opencpu). Opencpu works with `read.xlsx` and `write.xlsx` with no problem at all. But the performance of `read.xlsx2` and `write.xlsx2` is way better than corresponding "1-edition" functions, so it would awesome if opencpu can also work with the "2-edition" functions.

When I use `read.xlsx2`, I got error of 
```
OpenCPU error HTTP 400
java.lang.ClassNotFoundException

In call:
.jnew("org/cran/rexcel/RInterface")
```

The `write.xlsx2` returns error, 
```
OpenCPU error HTTP 400
class not found

In call:
.jfindClass(as.character(class))
```

I am no expert in Java, but when I read the help file of `read.xlsx2`, it say _The read.xlsx2 function does more work in Java so it achieves better performance (an order of magnitude faster on sheets with 100,000 cells or more). The result of read.xlsx2 will in general be different from read.xlsx, because internally read.xlsx2 uses readColumns which is tailored for tabular data._ Could it be some incompatibility between opencpu and Java?

Thanks.

**Comment by jeroenooms** [comment]
Java does not work well in OpenCPU. Try using [readxl](https://cran.r-project.org/web/packages/readxl/index.html) intead.
