### ISSUE TITLE
Keep json as string when passing it as a argument

### ISSUE THREAD

**Issue by bottleling** [jeroenooms/opencpu#219]
`myfunc <- function(arg){ ...}`

`curl -L -v -d '{"arg":{some_complex_json} }' -H "Content-Type: application/json" http://localhost/ocpu/library/mypkg/R/myfunc`

When posting arguments in json to OpenCPU, the server automatically converts the json string to list.  I would like to apply `jsonlite::fromJSON(some_complex_json, simplifyVector = FALSE, flatten=TRUE)` to my json string. How can I avoid the automatic conversion?

**Comment by nutle** [comment]
How did you solve it?

**Comment by jeroen** [comment]
You need to wrap it in quotes to make it a string.

**Comment by nutle** [comment]
But this would require tons of escaping, if I understand correctly.

Though, thinking about it, ``input %>% toJSON %>% fromJSON`` might do the trick. Thanks
